import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { doc, getDoc } from "firebase/firestore";
import styles from "../../styles/Home.module.css";
import { OrderFormValues, OrderStatus } from "../../models/order";
import { Button, Col, Form, Row, Table } from "react-bootstrap";
import { db } from "../../firebase";
import Link from "next/link";

const Orders: NextPage = () => {
  const [isOrdersLoading, setOrdersLoading] = useState(true);
  const defaultValues: OrderFormValues = {
    price: 0,
    description: "",
    status: OrderStatus.inProgress,
    createdAt: new Date(),
    completedAt: new Date(),
    payment: "",
    products: [],
    client: null,
  };

  const [formValues, setFormValues] = useState(defaultValues);

  const handleInputChange = (e: any) => {
    const { name, value } = e.target;
    setFormValues({
      ...formValues,
      [name]: value,
    });
  };

  const handleSubmit = (event: any) => {
    event.preventDefault();
    console.log(formValues);
  };

  useEffect(() => {
    const docRef = doc(db, "orders", "test");
    getDoc(docRef).then((doc) => {
      console.log(doc.data());
    });
  });

  const toDateInputValue = (date: Date) => {
    const local = new Date(date);
    local.setMinutes(date.getMinutes() - date.getTimezoneOffset());
    return local.toJSON().slice(0, 10);
  };

  return (
    <div className={styles.container} style={{ marginTop: "40px" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Row>
        <Col>
          <h1 className="mb-5">Orders</h1>
        </Col>
        <Col>
          <Link href={"/orders/add"}>
            <Button className="float-end">Add</Button>
          </Link>
        </Col>
      </Row>
      <Table striped bordered hover>
        <thead>
          <tr>
            <th>id</th>
            <th>price</th>
            <th>description</th>
            <th>status</th>
            <th>createdAt</th>
            <th>completedAt</th>
            <th>payment</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
            <td>@mdo</td>
            <td>@mdo</td>
            <td>@mdo</td>
          </tr>
        </tbody>
      </Table>
    </div>
  );
};

export default Orders;
