import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { db } from "../firebase";
import { doc, getDoc } from "firebase/firestore";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [isOrdersLoading, setOrdersLoading] = useState(true);
  useEffect(() => {
    const docRef = doc(db, "orders", "test");
    getDoc(docRef).then((doc) => {
      console.log(doc.data());
    });
  });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to s19049&apos;s mas project</h1>
      </main>
    </div>
  );
};

export default Home;
